### ISSUE TITLE
white/blacklist will not work under some situations

### ISSUE THREAD

**Issue by nobodyzxc** [nobodyzxc/drrr-botext#7]

**Comment by nobodyzxc** [comment]
banlist would miss 1 of 2 entering members when kicking someone

**Comment by shishiawase** [comment]
Don't banned users with tripcode, when ON "whitelist"

**Comment by nobodyzxc** [comment]
> Don't banned users with tripcode, when ON "whitelist"

use the rule: #.* can let anyone with tripcode join the room in whitelist setting

**Comment by shishiawase** [comment]
That is the problem. He allows people with a tripcode to pass without this rule: #.* and does not ban them, although he should ban.
This applies to the whitelist when there is no rule: #. *

**Comment by nobodyzxc** [comment]
it works well on my pc.
![tc](https://user-images.githubusercontent.com/17202064/92683164-c3793080-f364-11ea-9e50-b1aa9afe305c.gif)

**Comment by nobodyzxc** [comment]
> He allows people with a tripcode to pass without this rule: #.* and does not ban them, although he should ban.

nope, it ban them well on my pc, check the gif below.
I left whitelist rule as empty, which means it will ban everyone even they have tripcode.
![empty_rule](https://user-images.githubusercontent.com/17202064/92684259-a3973c00-f367-11ea-991e-19b9e55d4732.gif)

**Comment by nobodyzxc** [comment]
> He allows people with a tripcode to pass without this rule: #.* and does not ban them, although he should ban.

nope, it banned them well on my pc, check the gif below.
I left whitelist rule as empty, which means it will ban everyone even they have tripcode.

![tc](https://user-images.githubusercontent.com/17202064/92721937-6c418300-f399-11ea-996b-390b4e005e32.gif)

**Comment by shishiawase** [comment]
Hmm, that's weird. Yesterday let me enter, but today he doesn't. Everything was decided by itself. But thanks anyway for your feedback and help.~

**Comment by nobodyzxc** [comment]
Program behavior is deterministic, everything was decided by not only itself but also your input (manipulation).
The wrong situation may caused by your previous manipulation before your testing.
(which means that your manipulation may have already lead the extension into a error state by some bugs).

You can 
check the frontend console by clicking the f12 and 
check backend console from chrome://extensions -> extension/background page
There may exist some more useful information for debugging. (you can paste it for me next time, it may help)

I release the code, so you can load the pack by yourself and do the code fixing by yourself if you know some code.

I hope the extension can bring user some conding sense (the event action configuration is a small programming language, DSL)
and I open source it to make it more hackable, anyone know some javascript can modify it easily, 
I hope it can inspire someone's coding interest and help him start his coding travel.

finally, [this](https://discord.gg/cveZZTt) is our discussion channel, you can join it to get quicker reply.

**Comment by nobodyzxc** [comment]
> banlist would miss 1 of 2 entering members when kicking someone

fixed by replace jquery mouse clicking with ajax request.
